default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.32.0
    hooks:
      - id: check-metaschema
        files: ^static/schemas/.*\.json$
